# Generated by Django 3.0.5 on 2020-05-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_mcqresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqresponse',
            name='answer',
            field=models.CharField(max_length=300),
        ),
    ]
