# Generated by Django 3.0.5 on 2020-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_numrounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='rounds',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
