# Generated by Django 3.0.5 on 2020-04-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_numqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='numqs',
        ),
    ]
