# Generated by Django 3.0.5 on 2020-04-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_numqs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='numqs',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='rounds',
        ),
    ]
