# Generated by Django 3.0.5 on 2020-04-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200421_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
