# Generated by Django 3.0.5 on 2020-04-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiztakers_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztakers',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
